### ISSUE TITLE
Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by kierancrown** [frelei/VideoView#2]
I keep getting this when trying to pass a path in, the video file is there. Not sure what the issue is as I'm pretty new to Swift:

> Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

**Comment by frelei** [comment]
@kierancrown , I have to check to code to see what should be the issue. 
I have an idea about it, `if let videoURL = URL(string: url)`. The way we are initializing the `URL` is for remote videos, if you are loading a local file, the constructor maybe diferent.
